//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::chat::Entity as Chat;
pub use super::feed::Entity as Feed;
pub use super::message::Entity as Message;
pub use super::post::Entity as Post;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::user::Entity as User;
pub use super::user_chats::Entity as UserChats;
