//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "message_kind")]
pub enum MessageKind {
    #[sea_orm(string_value = "image")]
    Image,
    #[sea_orm(string_value = "text")]
    Text,
}
