//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub surname: String,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub password_hash: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl Related<super::link::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_links::Relation::Link.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_links::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
