query GetPosts {
  posts {
    edges {
      node {
        ...CurrentPost
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    nodes {
      ...CurrentPost
    }
  }
}

fragment CurrentPost on Post {
  id
  authorId
  parentId
  head
  title
  author {
    ...Author
  }
  content
  createdAt
  updatedAt
}

fragment Author on User {
  id
  name
  surname
  username
  email
  createdAt
  updatedAt
}