query UserPostsList($username: String, $first: Int, $last: Int, $after: Pxid, $before: Pxid) {
  user(filter: {username: $username}) {
    edges {
      node {
        ...Author
        posts(first: $first, last: $last, after: $after, before: $before) {
          edges {
            node {
              ...PostListFields
            }
          }
          pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
          }
        }
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}
