version: "3"

services:
  database:
    image: 'postgres:14.1-alpine'
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    env_file:
      - .env
    command: server --console-address ":9001" /data

  minio_client:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb --ignore-existing myminio/townhall;
      /usr/bin/mc anonymous set public myminio/townhall;
      exit 0;
      "

volumes:
  database:
  minio:
