mutation UserUpdate($input: UserUpdateInput!) {
  userUpdate(input: $input) {
    user {
      ...CurrentUser
    }
    error {
      code
      message
    }
  }
}

fragment CurrentUser on User {
  id
  name
  surname
  email
  username
  createdAt
  updatedAt
}
