query PostList($first: Int, $last: Int, $after: Pxid, $before: Pxid) {
  posts (first: $first, last: $last, after: $after, before: $before){
    edges {
      node {
        ...PostListFields
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}
