mutation PostCreate($input: PostCreateInput!) {
  postCreate(input: $input) {
    post {
      ...PostCreateFields
    }
    error {
      code
      message
    }
  }
}

fragment PostCreateFields on Post {
  id
  authorId
  parentId
  head
  title
  content
  createdAt
  updatedAt
}
